// ─── Catálogos estáticos (trazan normativa) ──────────────────────────────────
import type {
  AuditoriaItemVivo,
  HabilitacionItemDef,
  RequisitoDef,
} from './types'

export const HABILITACION_CATALOGO: HabilitacionItemDef[] = [
  // RECURSO HUMANO (6)
  {
    id: 'rh1',
    categoria: 'rh',
    descripcion:
      'Hojas de vida completas con soportes del personal asistencial',
    norma: 'Res. 3100/2019',
    auto: false,
  },
  {
    id: 'rh2',
    categoria: 'rh',
    descripcion: 'RethUS vigente de todo el personal de salud',
    norma: 'Res. 3100/2019',
    auto: false,
  },
  {
    id: 'rh3',
    categoria: 'rh',
    descripcion: 'Tarjetas profesionales vigentes verificadas en RUES',
    norma: 'Res. 3100/2019',
    auto: false,
  },
  {
    id: 'rh4',
    categoria: 'rh',
    descripcion: 'Inducción y re-inducción documentada del personal',
    norma: 'Res. 3100/2019',
    auto: true,
  },
  {
    id: 'rh5',
    categoria: 'rh',
    descripcion: 'Contratos o vinculaciones laborales vigentes',
    norma: 'Res. 3100/2019',
    auto: false,
  },
  {
    id: 'rh6',
    categoria: 'rh',
    descripcion: 'Certificados de aptitud médico-ocupacional vigentes',
    norma: 'Res. 3100/2019',
    auto: false,
  },
  // INFRAESTRUCTURA (7)
  {
    id: 'inf1',
    categoria: 'infra',
    descripcion: 'Planos de planta física actualizados y aprobados',
    norma: 'Res. 3100/2019',
    auto: false,
  },
  {
    id: 'inf2',
    categoria: 'infra',
    descripcion: 'Señalización de evacuación y extinción',
    norma: 'Res. 3100/2019',
    auto: false,
  },
  {
    id: 'inf3',
    categoria: 'infra',
    descripcion: 'Iluminación, ventilación y aseo verificados',
    norma: 'Res. 3100/2019',
    auto: false,
  },
  {
    id: 'inf4',
    categoria: 'infra',
    descripcion: 'Baños accesibles para usuarios con discapacidad',
    norma: 'Res. 3100/2019',
    auto: false,
  },
  {
    id: 'inf5',
    categoria: 'infra',
    descripcion:
      'Área diferenciada preparación y administración de medicamentos',
    norma: 'Res. 3100/2019',
    auto: false,
  },
  {
    id: 'inf6',
    categoria: 'infra',
    descripcion: 'Área de espera con condiciones dignas para usuarios',
    norma: 'Res. 3100/2019',
    auto: false,
  },
  {
    id: 'inf7',
    categoria: 'infra',
    descripcion:
      'Condiciones de bioseguridad y manejo de residuos hospitalarios',
    norma: 'Res. 3100/2019',
    auto: false,
  },
  // DOTACIÓN (6)
  {
    id: 'dot1',
    categoria: 'dotacion',
    descripcion: 'Inventario de equipos biomédicos actualizado',
    norma: 'Res. 3100/2019',
    auto: true,
  },
  {
    id: 'dot2',
    categoria: 'dotacion',
    descripcion: 'Hojas de vida de equipos biomédicos completas',
    norma: 'Res. 3100/2019',
    auto: true,
  },
  {
    id: 'dot3',
    categoria: 'dotacion',
    descripcion: 'Plan anual de mantenimientos preventivos activo',
    norma: 'Res. 3100 / Inv. 4702',
    auto: false,
  },
  {
    id: 'dot4',
    categoria: 'dotacion',
    descripcion: 'Calibraciones vigentes de equipos de medición',
    norma: 'Res. 3100/2019',
    auto: false,
  },
  {
    id: 'dot5',
    categoria: 'dotacion',
    descripcion: 'Registros Invima vigentes de equipos biomédicos',
    norma: 'Dec. 4725/2005',
    auto: false,
  },
  {
    id: 'dot6',
    categoria: 'dotacion',
    descripcion:
      'Dotación de insumos y medicamentos acorde a los servicios habilitados',
    norma: 'Res. 3100/2019',
    auto: false,
  },
  // PROCESOS (10)
  {
    id: 'pr1',
    categoria: 'procesos',
    descripcion: 'Manual de calidad actualizado',
    norma: 'Dec. 780/2016',
    auto: false,
  },
  {
    id: 'pr2',
    categoria: 'procesos',
    descripcion: 'Política de seguridad del paciente documentada',
    norma: 'Res. 256/2016',
    auto: false,
  },
  {
    id: 'pr3',
    categoria: 'procesos',
    descripcion: 'Protocolo de manejo de medicamentos de alto riesgo',
    norma: 'Res. 3100/2019',
    auto: false,
  },
  {
    id: 'pr4',
    categoria: 'procesos',
    descripcion: 'Procedimiento de referencia y contrarreferencia',
    norma: 'Res. 3100/2019',
    auto: false,
  },
  {
    id: 'pr5',
    categoria: 'procesos',
    descripcion: 'GPC Hemofilia adoptada y socializada',
    norma: 'Res. 3100/2019',
    auto: false,
  },
  {
    id: 'pr6',
    categoria: 'procesos',
    descripcion: 'Protocolo de manejo de eventos adversos',
    norma: 'Res. 256/2016',
    auto: false,
  },
  {
    id: 'pr7',
    categoria: 'procesos',
    descripcion: 'Procedimiento de gestión de PQR activo',
    norma: 'Res. 1552/2013',
    auto: false,
  },
  {
    id: 'pr8',
    categoria: 'procesos',
    descripcion: 'Protocolo de identificación correcta del paciente',
    norma: 'Res. 256/2016',
    auto: false,
  },
  {
    id: 'pr9',
    categoria: 'procesos',
    descripcion: 'Protocolo de administración segura de medicamentos',
    norma: 'Res. 3100/2019',
    auto: false,
  },
  {
    id: 'pr10',
    categoria: 'procesos',
    descripcion: 'Plan institucional de gestión del riesgo (PAMEC activo)',
    norma: 'Dec. 780/2016',
    auto: false,
  },
  // HABILITACIÓN REPS (5)
  {
    id: 'reps1',
    categoria: 'reps',
    descripcion: 'Inscripción REPS vigente y sin novedades pendientes',
    norma: 'Res. 3100/2019',
    auto: false,
  },
  {
    id: 'reps2',
    categoria: 'reps',
    descripcion: 'Servicios habilitados corresponden a los prestados',
    norma: 'Res. 3100/2019',
    auto: false,
  },
  {
    id: 'reps3',
    categoria: 'reps',
    descripcion: 'Responsable de calidad designado y documentado',
    norma: 'Dec. 780/2016',
    auto: false,
  },
  {
    id: 'reps4',
    categoria: 'reps',
    descripcion: 'Póliza de responsabilidad civil vigente',
    norma: 'Res. 3100/2019',
    auto: false,
  },
  {
    id: 'reps5',
    categoria: 'reps',
    descripcion:
      'Certificado de habilitación vigente (si aplica por Secretaría)',
    norma: 'Res. 3100/2019',
    auto: false,
  },
]

export const AUDITORIA_EN_VIVO_ITEMS: AuditoriaItemVivo[] = [
  // TALENTO HUMANO (5)
  {
    id: 'av_th1',
    categoria: 'talento_humano',
    descripcion: 'Hojas de vida físicas/digitales accesibles en sitio',
    normaReferencia: 'Res. 3100/2019',
  },
  {
    id: 'av_th2',
    categoria: 'talento_humano',
    descripcion: 'RethUS vigente para todo el personal asistencial presente',
    normaReferencia: 'Res. 3100/2019',
  },
  {
    id: 'av_th3',
    categoria: 'talento_humano',
    descripcion: 'Evidencia de inducción/re-inducción del personal',
    normaReferencia: 'Res. 3100/2019',
  },
  {
    id: 'av_th4',
    categoria: 'talento_humano',
    descripcion: 'Certificados BLS/ACLS vigentes donde aplica',
    normaReferencia: 'Res. 3100/2019',
  },
  {
    id: 'av_th5',
    categoria: 'talento_humano',
    descripcion: 'Esquema de vacunación ocupacional documentado',
    normaReferencia: 'Res. 3100/2019',
  },
  // EQUIPOS BIOMÉDICOS (5)
  {
    id: 'av_eq1',
    categoria: 'equipos',
    descripcion: 'Inventario físico de equipos coincide con registro',
    normaReferencia: 'Inv. 4702',
  },
  {
    id: 'av_eq2',
    categoria: 'equipos',
    descripcion: 'Cada equipo con hoja de vida técnica accesible',
    normaReferencia: 'Inv. 4702',
  },
  {
    id: 'av_eq3',
    categoria: 'equipos',
    descripcion: 'Etiqueta de último mantenimiento visible y vigente',
    normaReferencia: 'Inv. 4702',
  },
  {
    id: 'av_eq4',
    categoria: 'equipos',
    descripcion: 'Calibración vigente en equipos de medición',
    normaReferencia: 'Res. 3100/2019',
  },
  {
    id: 'av_eq5',
    categoria: 'equipos',
    descripcion: 'Registros Invima de equipos vigentes',
    normaReferencia: 'Dec. 4725/2005',
  },
  // INFRAESTRUCTURA (5)
  {
    id: 'av_inf1',
    categoria: 'infraestructura',
    descripcion: 'Señalización de evacuación visible y actualizada',
    normaReferencia: 'Res. 3100/2019',
  },
  {
    id: 'av_inf2',
    categoria: 'infraestructura',
    descripcion: 'Extintores vigentes y con recarga al día',
    normaReferencia: 'NFPA 10',
  },
  {
    id: 'av_inf3',
    categoria: 'infraestructura',
    descripcion: 'Baños accesibles limpios y funcionales',
    normaReferencia: 'Res. 3100/2019',
  },
  {
    id: 'av_inf4',
    categoria: 'infraestructura',
    descripcion: 'Iluminación y ventilación adecuadas en salas de atención',
    normaReferencia: 'Res. 3100/2019',
  },
  {
    id: 'av_inf5',
    categoria: 'infraestructura',
    descripcion: 'Cadena de frío verificada en medicamentos refrigerados',
    normaReferencia: 'Dec. 780/2016',
  },
  // PROCESOS Y DOCUMENTOS (6)
  {
    id: 'av_pd1',
    categoria: 'procesos_docs',
    descripcion: 'Manual de calidad disponible en sede',
    normaReferencia: 'Dec. 780/2016',
  },
  {
    id: 'av_pd2',
    categoria: 'procesos_docs',
    descripcion:
      'Protocolo de manejo de medicamentos de alto riesgo socializado',
    normaReferencia: 'Res. 3100/2019',
  },
  {
    id: 'av_pd3',
    categoria: 'procesos_docs',
    descripcion: 'GPC Hemofilia visible y socializada con evidencia',
    normaReferencia: 'Res. 3100/2019',
  },
  {
    id: 'av_pd4',
    categoria: 'procesos_docs',
    descripcion: 'Procedimiento PQR publicado en punto visible',
    normaReferencia: 'Res. 1552/2013',
  },
  {
    id: 'av_pd5',
    categoria: 'procesos_docs',
    descripcion: 'Plan de mejoramiento PAMEC vigente',
    normaReferencia: 'Dec. 780/2016',
  },
  {
    id: 'av_pd6',
    categoria: 'procesos_docs',
    descripcion: 'Registros de capacitación disponibles',
    normaReferencia: 'Res. 3100/2019',
  },
  // HABILITACIÓN REPS (3)
  {
    id: 'av_reps1',
    categoria: 'reps',
    descripcion: 'Certificado REPS visible y vigente',
    normaReferencia: 'Res. 3100/2019',
  },
  {
    id: 'av_reps2',
    categoria: 'reps',
    descripcion: 'Servicios prestados corresponden a los habilitados en REPS',
    normaReferencia: 'Res. 3100/2019',
  },
  {
    id: 'av_reps3',
    categoria: 'reps',
    descripcion: 'Responsable de calidad disponible para verificación',
    normaReferencia: 'Dec. 780/2016',
  },
  // SEGURIDAD DEL PACIENTE (4)
  {
    id: 'av_sp1',
    categoria: 'seguridad_paciente',
    descripcion:
      'Protocolo de identificación correcta del paciente en práctica',
    normaReferencia: 'Res. 256/2016',
  },
  {
    id: 'av_sp2',
    categoria: 'seguridad_paciente',
    descripcion: 'Reporte de eventos adversos activo con evidencia',
    normaReferencia: 'Res. 256/2016',
  },
  {
    id: 'av_sp3',
    categoria: 'seguridad_paciente',
    descripcion: 'Lavado de manos clínico observado en puntos críticos',
    normaReferencia: 'Res. 256/2016',
  },
  {
    id: 'av_sp4',
    categoria: 'seguridad_paciente',
    descripcion: 'Administración segura de medicamentos verificada',
    normaReferencia: 'Res. 3100/2019',
  },
]

// Requisitos documentales por cargo. Claves = Cargo.id (MD, ENF, AUX_ENF, QF, ADM, COORD_CAL)
export const REQUISITOS_POR_CARGO: Record<string, RequisitoDef[]> = {
  MD: [
    {
      id: 'rq_rethus',
      nombre: 'RethUS vigente',
      norma: 'Res. 3100/2019',
      categoria: 'normativo',
      critico: true,
    },
    {
      id: 'rq_tp',
      nombre: 'Tarjeta Profesional Médica',
      norma: 'Res. 3100/2019',
      categoria: 'normativo',
      critico: true,
    },
    {
      id: 'rq_diploma',
      nombre: 'Diploma de Médico Cirujano',
      norma: 'Res. 3100/2019',
      categoria: 'hojas_vida',
      critico: true,
    },
    {
      id: 'rq_acta_grado',
      nombre: 'Acta de grado',
      norma: 'Res. 3100/2019',
      categoria: 'hojas_vida',
      critico: true,
    },
    {
      id: 'rq_especializacion',
      nombre: 'Diploma especialización',
      norma: 'Res. 3100/2019',
      categoria: 'hojas_vida',
      critico: true,
    },
    {
      id: 'rq_acta_esp',
      nombre: 'Acta de grado especialización',
      norma: 'Res. 3100/2019',
      categoria: 'hojas_vida',
      critico: true,
    },
    {
      id: 'rq_convalidacion',
      nombre: 'Convalidación de título (si es extranjero)',
      norma: 'Res. 3100/2019',
      categoria: 'hojas_vida',
      critico: false,
    },
    {
      id: 'rq_acls',
      nombre: 'Soporte Vital Avanzado (ACLS)',
      norma: 'Res. 3100/2019',
      categoria: 'capacitacion',
      critico: true,
    },
    {
      id: 'rq_bls',
      nombre: 'Soporte Vital Básico (BLS)',
      norma: 'Res. 3100/2019',
      categoria: 'capacitacion',
      critico: true,
    },
    {
      id: 'rq_gpc',
      nombre: 'GPC Hemofilia socializada',
      norma: 'Res. 3100/2019',
      categoria: 'capacitacion',
      critico: true,
    },
    {
      id: 'rq_violencia',
      nombre: 'Curso violencia sexual (R. 459/2012)',
      norma: 'Res. 459/2012',
      categoria: 'capacitacion',
      critico: true,
    },
    {
      id: 'rq_humanizacion',
      nombre: 'Curso humanización en salud',
      norma: 'Res. 3100/2019',
      categoria: 'capacitacion',
      critico: true,
    },
    {
      id: 'rq_seguridad',
      nombre: 'Curso seguridad del paciente',
      norma: 'Res. 256/2016',
      categoria: 'capacitacion',
      critico: true,
    },
    {
      id: 'rq_vacunas',
      nombre: 'Esquema vacunación (HepB/Tétano/Influenza/Covid)',
      norma: 'Res. 3100/2019',
      categoria: 'vacuna',
      critico: true,
    },
    {
      id: 'rq_hv_formato',
      nombre: 'Hoja de vida formato institucional',
      norma: 'Res. 3100/2019',
      categoria: 'hojas_vida',
      critico: true,
    },
    {
      id: 'rq_qt',
      nombre: 'Manejo quimioterapia segura',
      norma: 'Res. 3100/2019',
      categoria: 'capacitacion',
      critico: false,
    },
  ],
  ENF: [
    {
      id: 'rq_tp_enf',
      nombre: 'Tarjeta Profesional Enfermería',
      norma: 'Res. 3100/2019',
      categoria: 'normativo',
      critico: true,
    },
    {
      id: 'rq_rethus_enf',
      nombre: 'RethUS vigente',
      norma: 'Res. 3100/2019',
      categoria: 'normativo',
      critico: true,
    },
    {
      id: 'rq_diploma_enf',
      nombre: 'Diploma profesional en Enfermería',
      norma: 'Res. 3100/2019',
      categoria: 'hojas_vida',
      critico: true,
    },
    {
      id: 'rq_acta_grado_enf',
      nombre: 'Acta de grado',
      norma: 'Res. 3100/2019',
      categoria: 'hojas_vida',
      critico: true,
    },
    {
      id: 'rq_convalidacion_enf',
      nombre: 'Convalidación de título (si es extranjero)',
      norma: 'Res. 3100/2019',
      categoria: 'hojas_vida',
      critico: false,
    },
    {
      id: 'rq_acls_enf',
      nombre: 'Soporte Vital Avanzado (ACLS)',
      norma: 'Res. 3100/2019',
      categoria: 'capacitacion',
      critico: true,
    },
    {
      id: 'rq_ams_enf',
      nombre: 'Manejo medicamentos alto riesgo',
      norma: 'Res. 3100/2019',
      categoria: 'capacitacion',
      critico: true,
    },
    {
      id: 'rq_venosos_enf',
      nombre: 'Manejo de accesos venosos',
      norma: 'Res. 3100/2019',
      categoria: 'capacitacion',
      critico: true,
    },
    {
      id: 'rq_violencia_enf',
      nombre: 'Curso violencia sexual (R. 459/2012)',
      norma: 'Res. 459/2012',
      categoria: 'capacitacion',
      critico: true,
    },
    {
      id: 'rq_vacunas_enf',
      nombre: 'Esquema vacunación (HepB/Tétano/Influenza/Covid)',
      norma: 'Res. 3100/2019',
      categoria: 'vacuna',
      critico: true,
    },
    {
      id: 'rq_hv_formato_enf',
      nombre: 'Hoja de vida formato institucional',
      norma: 'Res. 3100/2019',
      categoria: 'hojas_vida',
      critico: true,
    },
    {
      id: 'rq_bls_enf',
      nombre: 'Soporte Vital Básico (BLS)',
      norma: 'Res. 3100/2019',
      categoria: 'capacitacion',
      critico: true,
    },
  ],
  AUX_ENF: [
    {
      id: 'rq_titulo_aux',
      nombre: 'Título Técnico en Auxiliar de Enfermería',
      norma: 'Res. 3100/2019',
      categoria: 'hojas_vida',
      critico: true,
    },
    {
      id: 'rq_rethus_aux',
      nombre: 'RethUS vigente',
      norma: 'Res. 3100/2019',
      categoria: 'normativo',
      critico: true,
    },
    {
      id: 'rq_bls_aux',
      nombre: 'Soporte Vital Básico (BLS)',
      norma: 'Res. 3100/2019',
      categoria: 'capacitacion',
      critico: true,
    },
    {
      id: 'rq_bio_aux',
      nombre: 'Bioseguridad y residuos hospitalarios',
      norma: 'Res. 3100/2019',
      categoria: 'capacitacion',
      critico: true,
    },
    {
      id: 'rq_vacunas_aux',
      nombre: 'Esquema vacunación',
      norma: 'Res. 3100/2019',
      categoria: 'vacuna',
      critico: true,
    },
    {
      id: 'rq_hv_formato_aux',
      nombre: 'Hoja de vida formato institucional',
      norma: 'Res. 3100/2019',
      categoria: 'hojas_vida',
      critico: true,
    },
    {
      id: 'rq_humanizacion_aux',
      nombre: 'Curso humanización en salud',
      norma: 'Res. 3100/2019',
      categoria: 'capacitacion',
      critico: true,
    },
  ],
  QF: [
    {
      id: 'rq_tp_qf',
      nombre: 'Tarjeta Profesional Químico Farmacéutico',
      norma: 'Res. 3100/2019',
      categoria: 'normativo',
      critico: true,
    },
    {
      id: 'rq_rethus_qf',
      nombre: 'RethUS vigente',
      norma: 'Res. 3100/2019',
      categoria: 'normativo',
      critico: true,
    },
    {
      id: 'rq_diploma_qf',
      nombre: 'Diploma Químico Farmacéutico',
      norma: 'Res. 3100/2019',
      categoria: 'hojas_vida',
      critico: true,
    },
    {
      id: 'rq_cadena',
      nombre: 'Cadena de frío y almacenamiento',
      norma: 'Res. 3100/2019',
      categoria: 'capacitacion',
      critico: true,
    },
    {
      id: 'rq_ams_qf',
      nombre: 'Manejo medicamentos alto riesgo',
      norma: 'Res. 3100/2019',
      categoria: 'capacitacion',
      critico: true,
    },
    {
      id: 'rq_cito',
      nombre: 'Manejo de citotóxicos',
      norma: 'Res. 3100/2019',
      categoria: 'capacitacion',
      critico: true,
    },
    {
      id: 'rq_vacunas_qf',
      nombre: 'Esquema vacunación',
      norma: 'Res. 3100/2019',
      categoria: 'vacuna',
      critico: true,
    },
    {
      id: 'rq_hv_formato_qf',
      nombre: 'Hoja de vida formato institucional',
      norma: 'Res. 3100/2019',
      categoria: 'hojas_vida',
      critico: true,
    },
    {
      id: 'rq_fv',
      nombre: 'Farmacovigilancia (Res. 2004/2008)',
      norma: 'Res. 2004/2008',
      categoria: 'capacitacion',
      critico: true,
    },
  ],
  ADM: [
    {
      id: 'rq_titulo_adm',
      nombre: 'Título técnico o tecnólogo',
      norma: 'Res. 3100/2019',
      categoria: 'hojas_vida',
      critico: true,
    },
    {
      id: 'rq_atn_usuario',
      nombre: 'Curso atención al usuario',
      norma: 'Res. 3100/2019',
      categoria: 'capacitacion',
      critico: true,
    },
    {
      id: 'rq_hc_adm',
      nombre: 'Manejo historia clínica (Res. 1995/1999)',
      norma: 'Res. 1995/1999',
      categoria: 'capacitacion',
      critico: true,
    },
    {
      id: 'rq_hv_formato_adm',
      nombre: 'Hoja de vida formato institucional',
      norma: 'Res. 3100/2019',
      categoria: 'hojas_vida',
      critico: true,
    },
  ],
  COORD_CAL: [
    {
      id: 'rq_titulo_cc',
      nombre: 'Título profesional área de salud',
      norma: 'Dec. 780/2016',
      categoria: 'hojas_vida',
      critico: true,
    },
    {
      id: 'rq_tp_cc',
      nombre: 'Tarjeta profesional vigente',
      norma: 'Res. 3100/2019',
      categoria: 'normativo',
      critico: true,
    },
    {
      id: 'rq_iso_cc',
      nombre: 'Curso normas ISO / gestión de calidad',
      norma: 'Dec. 780/2016',
      categoria: 'capacitacion',
      critico: true,
    },
    {
      id: 'rq_audit_cc',
      nombre: 'Curso auditoría interna',
      norma: 'Dec. 780/2016',
      categoria: 'capacitacion',
      critico: true,
    },
  ],
}
