// ─── Seed data — migrated from StackBlitz prototype ─────────────────────────
import type {
  Usuario,
  Sede,
  Cargo,
  Persona,
  Equipo,
  Habilitacion,
  Indicador,
  MedicionIndicador,
  AccionPAMEC,
  Auditoria,
  Documento,
  Medicamento,
  Proceso,
  PQRS,
  Adherencia,
} from './types'

export const USUARIOS: Usuario[] = [
  {
    id: 'u1',
    nombre: 'Administrador SGC',
    email: 'admin@betania.com',
    rol: 'admin',
    sede: 'BAQ',
    clave: 'admin123',
  },
  {
    id: 'u2',
    nombre: 'Coordinadora Calidad',
    email: 'calidad@betania.com',
    rol: 'calidad',
    sede: 'BAQ',
    clave: 'calidad123',
  },
  {
    id: 'u3',
    nombre: 'Director Médico',
    email: 'director@betania.com',
    rol: 'director',
    sede: 'BAQ',
    clave: 'dir123',
  },
]

export const SEDES0: Sede[] = [
  {
    id: 'BAQ',
    nombre: 'Betania Barranquilla',
    ciudad: 'Barranquilla',
    direccion: 'Cra. 38 #79-25',
    activa: true,
  },
  {
    id: 'SIN',
    nombre: 'Betania Sincelejo',
    ciudad: 'Sincelejo',
    direccion: 'Cl. 20 #25-30',
    activa: true,
  },
  {
    id: 'STM',
    nombre: 'Betania Santa Marta',
    ciudad: 'Santa Marta',
    direccion: 'Av. del Río #15-40',
    activa: true,
  },
  {
    id: 'MTR',
    nombre: 'Betania Montería',
    ciudad: 'Montería',
    direccion: 'Cl. 28 #5-60',
    activa: true,
  },
]

export const CARGOS0: Cargo[] = [
  {
    id: 'MD',
    nombre: 'Médico',
    area: 'Asistencial',
    perfil: 'Médico Cirujano con experiencia en hematología u oncología',
    docRequeridos: [
      'tarjeta_profesional',
      'rethus',
      'poliza',
      'curso_soporte_vital',
    ],
    capRequeridas: [
      'bioseguridad',
      'manejo_residuos',
      'atencion_centrada_paciente',
    ],
  },
  {
    id: 'ENF',
    nombre: 'Enfermera/o',
    area: 'Asistencial',
    perfil: 'Enfermero/a titulado con RETHUS vigente',
    docRequeridos: ['tarjeta_profesional', 'rethus', 'poliza'],
    capRequeridas: ['bioseguridad', 'manejo_residuos', 'venopuncion'],
  },
  {
    id: 'AUX_ENF',
    nombre: 'Auxiliar de Enfermería',
    area: 'Asistencial',
    perfil: 'Técnico en auxiliar de enfermería',
    docRequeridos: ['titulo_tecnico', 'rethus'],
    capRequeridas: ['bioseguridad', 'manejo_residuos'],
  },
  {
    id: 'QF',
    nombre: 'Químico Farmacéutico',
    area: 'Farmacia',
    perfil: 'Químico Farmacéutico titulado con tarjeta profesional vigente',
    docRequeridos: ['tarjeta_profesional', 'rethus', 'poliza'],
    capRequeridas: ['cadena_frio', 'manejo_citotoxicos', 'dispensacion'],
  },
  {
    id: 'ADM',
    nombre: 'Auxiliar Administrativo',
    area: 'Administrativo',
    perfil: 'Técnico o tecnólogo en área administrativa o de salud',
    docRequeridos: ['titulo_tecnico'],
    capRequeridas: ['atencion_usuario', 'manejo_historia_clinica'],
  },
  {
    id: 'COORD_CAL',
    nombre: 'Coordinador de Calidad',
    area: 'Calidad',
    perfil: 'Profesional de salud con formación en gestión de calidad',
    docRequeridos: ['titulo_profesional', 'tarjeta_profesional'],
    capRequeridas: ['normas_iso', 'auditoria_interna', 'indicadores'],
  },
]

export const PERS0: Persona[] = [
  {
    id: 'p1',
    nombre: 'Dra. Carolina Martínez',
    cedula: '22445566',
    cargo: 'MD',
    sede: 'BAQ',
    fechaIngreso: '2020-03-01',
    estado: 'activo',
    docs: [
      {
        tipo: 'tarjeta_profesional',
        numero: 'TP-12345',
        fechaExp: '2015-06-01',
        fechaVenc: null,
      },
      {
        tipo: 'rethus',
        numero: 'RE-67890',
        fechaExp: '2023-01-15',
        fechaVenc: '2025-01-15',
      },
      { tipo: 'poliza', fechaExp: '2024-01-01', fechaVenc: '2025-01-01' },
      {
        tipo: 'curso_soporte_vital',
        fechaExp: '2023-06-10',
        fechaVenc: '2025-06-10',
      },
    ],
    caps: [
      {
        tema: 'bioseguridad',
        fecha: '2024-02-20',
        horas: 4,
        entidad: 'Betania',
      },
      {
        tema: 'manejo_residuos',
        fecha: '2024-02-20',
        horas: 2,
        entidad: 'Betania',
      },
      {
        tema: 'atencion_centrada_paciente',
        fecha: '2023-09-15',
        horas: 8,
        entidad: 'Betania',
      },
    ],
  },
  {
    id: 'p2',
    nombre: 'Enf. Jorge Paredes',
    cedula: '33556677',
    cargo: 'ENF',
    sede: 'BAQ',
    fechaIngreso: '2021-07-01',
    estado: 'activo',
    docs: [
      {
        tipo: 'tarjeta_profesional',
        numero: 'TP-54321',
        fechaExp: '2017-08-10',
        fechaVenc: null,
      },
      {
        tipo: 'rethus',
        numero: 'RE-11223',
        fechaExp: '2022-03-20',
        fechaVenc: '2024-03-20',
      },
      { tipo: 'poliza', fechaExp: '2024-01-01', fechaVenc: '2025-01-01' },
    ],
    caps: [
      {
        tema: 'bioseguridad',
        fecha: '2024-02-20',
        horas: 4,
        entidad: 'Betania',
      },
      {
        tema: 'manejo_residuos',
        fecha: '2024-02-20',
        horas: 2,
        entidad: 'Betania',
      },
    ],
  },
  {
    id: 'p3',
    nombre: 'QF. Ana Suárez',
    cedula: '44667788',
    cargo: 'QF',
    sede: 'BAQ',
    fechaIngreso: '2022-01-10',
    estado: 'activo',
    docs: [
      {
        tipo: 'tarjeta_profesional',
        numero: 'TP-99887',
        fechaExp: '2018-05-05',
        fechaVenc: null,
      },
      {
        tipo: 'rethus',
        numero: 'RE-44556',
        fechaExp: '2023-11-01',
        fechaVenc: '2025-11-01',
      },
      { tipo: 'poliza', fechaExp: '2024-01-01', fechaVenc: '2025-01-01' },
    ],
    caps: [
      {
        tema: 'cadena_frio',
        fecha: '2024-03-10',
        horas: 6,
        entidad: 'ANDI Pharma',
      },
      {
        tema: 'manejo_citotoxicos',
        fecha: '2024-03-10',
        horas: 8,
        entidad: 'Betania',
      },
      {
        tema: 'dispensacion',
        fecha: '2023-09-20',
        horas: 4,
        entidad: 'Betania',
      },
    ],
  },
  {
    id: 'p4',
    nombre: 'Aux. Laura Gómez',
    cedula: '55778899',
    cargo: 'ADM',
    sede: 'SIN',
    fechaIngreso: '2021-09-15',
    estado: 'activo',
    docs: [{ tipo: 'titulo_tecnico', fechaExp: '2019-11-20', fechaVenc: null }],
    caps: [
      {
        tema: 'atencion_usuario',
        fecha: '2024-01-15',
        horas: 4,
        entidad: 'Betania',
      },
    ],
  },
  {
    id: 'p5',
    nombre: 'Enf. Pedro Llanos',
    cedula: '66889900',
    cargo: 'ENF',
    sede: 'STM',
    fechaIngreso: '2020-06-01',
    estado: 'activo',
    docs: [
      {
        tipo: 'tarjeta_profesional',
        numero: 'TP-77654',
        fechaExp: '2016-07-01',
        fechaVenc: null,
      },
      {
        tipo: 'rethus',
        numero: 'RE-33441',
        fechaExp: '2021-05-10',
        fechaVenc: '2023-05-10',
      },
      { tipo: 'poliza', fechaExp: '2023-01-01', fechaVenc: '2024-01-01' },
    ],
    caps: [
      {
        tema: 'bioseguridad',
        fecha: '2023-02-20',
        horas: 4,
        entidad: 'Betania',
      },
    ],
  },
]

export const EQS0: Equipo[] = [
  {
    id: 'eq1',
    nombre: 'Bomba de Infusión Volumétrica',
    marca: 'Baxter',
    modelo: 'Colleague CX',
    serie: 'CX-2024-001',
    sede: 'BAQ',
    area: 'Oncología',
    fechaCompra: '2022-03-15',
    ultimaMant: '2024-09-01',
    proxMant: '2025-03-01',
    estado: 'operativo',
    invima: 'INVIMA 2021DM-0001',
    vida: 10,
    prioridad: 'alta',
    docs: [],
  },
  {
    id: 'eq2',
    nombre: 'Centrífuga de Laboratorio',
    marca: 'Eppendorf',
    modelo: '5804R',
    serie: 'EP-5804-0987',
    sede: 'BAQ',
    area: 'Laboratorio',
    fechaCompra: '2021-08-20',
    ultimaMant: '2024-06-15',
    proxMant: '2024-12-15',
    estado: 'operativo',
    invima: 'INVIMA 2020DM-0123',
    vida: 15,
    prioridad: 'media',
    docs: [],
  },
  {
    id: 'eq3',
    nombre: 'Monitor de Signos Vitales',
    marca: 'Philips',
    modelo: 'IntelliVue MX450',
    serie: 'PH-MX450-3456',
    sede: 'SIN',
    area: 'Urgencias',
    fechaCompra: '2023-01-10',
    ultimaMant: '2024-07-10',
    proxMant: '2025-01-10',
    estado: 'operativo',
    invima: 'INVIMA 2022DM-0456',
    vida: 10,
    prioridad: 'alta',
    docs: [],
  },
  {
    id: 'eq4',
    nombre: 'Autoclave de Mesa',
    marca: 'Tuttnauer',
    modelo: '2340M',
    serie: 'TU-2340-7891',
    sede: 'STM',
    area: 'Esterilización',
    fechaCompra: '2020-05-05',
    ultimaMant: '2024-05-05',
    proxMant: '2024-11-05',
    estado: 'mantenimiento',
    invima: 'INVIMA 2019DM-0789',
    vida: 20,
    prioridad: 'alta',
    docs: [],
  },
]

export const HAB0: Record<string, Habilitacion> = {
  BAQ: {
    sedeId: 'BAQ',
    fechaRevision: '2025-01-15',
    responsable: 'Coordinadora Calidad',
    items: [
      {
        id: 'h1',
        criterio: 'Recurso Humano',
        estandar: 'Talento humano habilitado y documentado',
        estado: 'cumple',
        observacion: 'Todo el personal con documentos vigentes',
      },
      {
        id: 'h2',
        criterio: 'Dotación',
        estandar:
          'Equipos biomédicos calibrados y con mantenimiento preventivo',
        estado: 'parcial',
        observacion: 'Pendiente calibración de 2 equipos',
      },
      {
        id: 'h3',
        criterio: 'Medicamentos',
        estandar: 'Almacenamiento y dispensación bajo norma',
        estado: 'cumple',
        observacion: '',
      },
      {
        id: 'h4',
        criterio: 'Procesos Prioritarios',
        estandar: 'Procedimientos documentados y socializados',
        estado: 'cumple',
        observacion: '',
      },
      {
        id: 'h5',
        criterio: 'Historia Clínica',
        estandar: 'Manejo de HC conforme a Res. 1995/1999',
        estado: 'cumple',
        observacion: '',
      },
      {
        id: 'h6',
        criterio: 'Interdependencias',
        estandar: 'Contratos y convenios vigentes',
        estado: 'parcial',
        observacion: 'Convenio laboratorio por renovar',
      },
    ],
  },
  SIN: {
    sedeId: 'SIN',
    fechaRevision: '2025-01-10',
    responsable: 'Coordinador Sincelejo',
    items: [
      {
        id: 'h1',
        criterio: 'Recurso Humano',
        estandar: 'Talento humano habilitado y documentado',
        estado: 'parcial',
        observacion: 'Aux. admnistrativa con cap. pendiente',
      },
      {
        id: 'h2',
        criterio: 'Dotación',
        estandar:
          'Equipos biomédicos calibrados y con mantenimiento preventivo',
        estado: 'cumple',
        observacion: '',
      },
      {
        id: 'h3',
        criterio: 'Medicamentos',
        estandar: 'Almacenamiento y dispensación bajo norma',
        estado: 'cumple',
        observacion: '',
      },
      {
        id: 'h4',
        criterio: 'Procesos Prioritarios',
        estandar: 'Procedimientos documentados y socializados',
        estado: 'no_cumple',
        observacion: 'Falta socializar 3 procedimientos nuevos',
      },
    ],
  },
}

export const INDIC_DEF: Indicador[] = [
  {
    id: 'i1',
    nombre: 'Oportunidad de la Atención',
    descripcion: 'Tiempo promedio entre solicitud y primera cita',
    formula: '(Total días espera / Total pacientes nuevos) × 100',
    meta: 5,
    unidad: 'días',
    frecuencia: 'mensual',
    proceso: 'Atención al paciente',
    responsable: 'Coordinadora Calidad',
  },
  {
    id: 'i2',
    nombre: 'Tasa de Infección Asociada a Catéter',
    descripcion: 'Infecciones por 1000 días catéter',
    formula: '(N° infecciones / Días catéter) × 1000',
    meta: 2,
    unidad: 'por 1000 días',
    frecuencia: 'mensual',
    proceso: 'Seguridad del paciente',
    responsable: 'Jefe de Enfermería',
  },
  {
    id: 'i3',
    nombre: 'Cumplimiento Capacitaciones',
    descripcion: '% personal con plan de capacitación al día',
    formula: '(Personal capacitado / Total personal) × 100',
    meta: 90,
    unidad: '%',
    frecuencia: 'trimestral',
    proceso: 'Gestión del Talento Humano',
    responsable: 'Coordinadora Calidad',
  },
  {
    id: 'i4',
    nombre: 'PQRS Respondidas Oportunamente',
    descripcion: '% PQRS respondidas dentro del tiempo legal (15 días)',
    formula: '(PQRS respondidas a tiempo / Total PQRS) × 100',
    meta: 95,
    unidad: '%',
    frecuencia: 'mensual',
    proceso: 'Atención al usuario',
    responsable: 'Auxiliar Administrativo',
  },
  {
    id: 'i5',
    nombre: 'Adherencia a Protocolos',
    descripcion: '% de aplicaciones de protocolo conformes',
    formula: '(Aplicaciones conformes / Total aplicaciones) × 100',
    meta: 90,
    unidad: '%',
    frecuencia: 'trimestral',
    proceso: 'Procesos asistenciales',
    responsable: 'Jefe de Enfermería',
  },
]

export const MEDICIONES0: MedicionIndicador[] = [
  {
    indicadorId: 'i1',
    periodo: '2025-01',
    valor: 4.2,
    meta: 5,
    observacion: 'Dentro de meta',
    responsable: 'Coordinadora Calidad',
    fecha: '2025-02-05',
  },
  {
    indicadorId: 'i2',
    periodo: '2025-01',
    valor: 1.8,
    meta: 2,
    observacion: 'Dentro de meta',
    responsable: 'Jefe de Enfermería',
    fecha: '2025-02-05',
  },
  {
    indicadorId: 'i3',
    periodo: '2025-T1',
    valor: 78,
    meta: 90,
    observacion: 'Por debajo de meta — plan de acción en curso',
    responsable: 'Coordinadora Calidad',
    fecha: '2025-04-05',
  },
  {
    indicadorId: 'i4',
    periodo: '2025-01',
    valor: 100,
    meta: 95,
    observacion: 'Todas las PQRS respondidas oportunamente',
    responsable: 'Aux. Administrativa',
    fecha: '2025-02-05',
  },
  {
    indicadorId: 'i5',
    periodo: '2025-T1',
    valor: 85,
    meta: 90,
    observacion: 'Levemente por debajo de meta',
    responsable: 'Jefe de Enfermería',
    fecha: '2025-04-10',
  },
]

export const PLAN_MEJORA0: AccionPAMEC[] = [
  {
    id: 'am1',
    hallazgo: 'Capacitaciones de personal por debajo del 90%',
    causa: 'Alta rotación de personal y falta de cronograma formal',
    accion:
      'Elaborar cronograma anual de capacitaciones y designar responsable por sede',
    responsable: 'Coordinadora Calidad',
    fechaLimite: '2025-04-30',
    estado: 'en_proceso',
    fase: 'planear',
    sede: 'BAQ',
  },
  {
    id: 'am2',
    hallazgo: 'Dos equipos sin calibración vigente',
    causa: 'Proveedor de calibración no disponible en el periodo',
    accion: 'Contratar nuevo proveedor acreditado y programar calibraciones',
    responsable: 'Coordinadora Calidad',
    fechaLimite: '2025-03-31',
    estado: 'cerrado',
    fechaCierre: '2025-03-20',
    resultado: 'Se contrató proveedor Metrología S.A. — equipos calibrados',
    fase: 'hacer',
    sede: 'BAQ',
  },
  {
    id: 'am3',
    hallazgo: 'Protocolos no socializados en sede Sincelejo',
    causa: 'Actualización de protocolos sin proceso formal de socialización',
    accion:
      'Realizar jornada de socialización y evidenciar con registro de asistencia',
    responsable: 'Coordinador Sincelejo',
    fechaLimite: '2025-05-15',
    estado: 'pendiente',
    fase: 'hacer',
    sede: 'SIN',
  },
]

export const AUDITORIAS0: Auditoria[] = [
  {
    id: 'aud1',
    tipo: 'interna',
    proceso: 'Atención al paciente',
    sede: 'BAQ',
    auditor: 'Coordinadora Calidad',
    fechaInicio: '2025-02-10',
    fechaFin: '2025-02-14',
    estado: 'cerrada',
    hallazgos: [
      {
        id: 'h1',
        tipo: 'observacion',
        descripcion:
          'Tiempos de espera documentados pero sin análisis de causa raíz mensual',
        criterio: 'Procedimiento de atención P-001 v3',
        estado: 'cerrado',
        accionCorrectiva: 'Incluir análisis de causa en informe mensual',
        responsable: 'Coordinadora Calidad',
        fechaLimite: '2025-03-31',
      },
    ],
    observaciones:
      'Proceso en general conforme. Se identificó oportunidad de mejora.',
  },
]

export const DOCS0: Documento[] = [
  {
    id: 'd1',
    codigo: 'M-SGC-001',
    nombre: 'Manual del Sistema de Gestión de Calidad',
    tipo: 'manual',
    proceso: 'Gestión de Calidad',
    version: '3.0',
    fechaElaboracion: '2024-01-10',
    fechaVigencia: '2026-01-10',
    responsable: 'Coordinadora Calidad',
    estado: 'vigente',
  },
  {
    id: 'd2',
    codigo: 'P-ATN-001',
    nombre: 'Procedimiento de Atención al Paciente Oncológico',
    tipo: 'procedimiento',
    proceso: 'Atención al paciente',
    version: '3.0',
    fechaElaboracion: '2024-03-01',
    fechaVigencia: '2026-03-01',
    responsable: 'Director Médico',
    estado: 'vigente',
  },
  {
    id: 'd3',
    codigo: 'P-FAR-001',
    nombre: 'Procedimiento de Dispensación de Medicamentos',
    tipo: 'procedimiento',
    proceso: 'Farmacia',
    version: '2.1',
    fechaElaboracion: '2023-06-15',
    fechaVigencia: '2025-06-15',
    responsable: 'QF. Ana Suárez',
    estado: 'vigente',
  },
  {
    id: 'd4',
    codigo: 'I-BSG-001',
    nombre: 'Instructivo de Bioseguridad y Manejo de Residuos',
    tipo: 'instructivo',
    proceso: 'Gestión Ambiental',
    version: '1.2',
    fechaElaboracion: '2024-02-01',
    fechaVigencia: '2026-02-01',
    responsable: 'Coordinadora Calidad',
    estado: 'vigente',
  },
  {
    id: 'd5',
    codigo: 'F-RH-001',
    nombre: 'Formato Evaluación de Desempeño',
    tipo: 'formato',
    proceso: 'Gestión del Talento Humano',
    version: '2.0',
    fechaElaboracion: '2024-01-15',
    fechaVigencia: '2026-01-15',
    responsable: 'Coordinadora Calidad',
    estado: 'vigente',
  },
]

export const MEDS0: Medicamento[] = [
  {
    id: 'm1',
    nombre: 'Rituximab 500mg/50mL',
    principioActivo: 'Rituximab',
    concentracion: '10mg/mL',
    forma: 'Solución para infusión',
    laboratorio: 'Roche',
    registro: 'INVIMA 2019M-0001',
    lote: 'RT2024001',
    fechaVenc: '2025-09-30',
    stock: 12,
    stockMinimo: 3,
    sede: 'BAQ',
    condicionAlm: 'Refrigeración 2-8°C',
    estado: 'activo',
  },
  {
    id: 'm2',
    nombre: 'Metotrexato 50mg/2mL',
    principioActivo: 'Metotrexato',
    concentracion: '25mg/mL',
    forma: 'Solución inyectable',
    laboratorio: 'Sandoz',
    registro: 'INVIMA 2018M-0234',
    lote: 'MX2024007',
    fechaVenc: '2025-06-30',
    stock: 8,
    stockMinimo: 5,
    sede: 'BAQ',
    condicionAlm: 'Temperatura ambiente 15-25°C, protegido de la luz',
    estado: 'activo',
  },
  {
    id: 'm3',
    nombre: 'Factor VIII 1000UI',
    principioActivo: 'Factor VIII de coagulación',
    concentracion: '1000UI/vial',
    forma: 'Polvo para inyección',
    laboratorio: 'Bayer',
    registro: 'INVIMA 2021M-0567',
    lote: 'FV2024003',
    fechaVenc: '2025-12-31',
    stock: 2,
    stockMinimo: 5,
    sede: 'SIN',
    condicionAlm: 'Refrigeración 2-8°C',
    estado: 'activo',
  },
]

export const PROCESOS0: Proceso[] = [
  {
    id: 'pr1',
    nombre: 'Dirección Estratégica',
    tipo: 'estrategico',
    responsable: 'Director Médico',
    objetivo: 'Definir el direccionamiento estratégico y garantizar el SGC',
    indicadores: ['i3'],
    documentos: ['d1'],
    riesgos: [],
  },
  {
    id: 'pr2',
    nombre: 'Atención al Paciente',
    tipo: 'misional',
    responsable: 'Director Médico',
    objetivo: 'Brindar atención oportuna y segura al paciente oncohematológico',
    indicadores: ['i1', 'i2', 'i5'],
    documentos: ['d2'],
    riesgos: [],
  },
  {
    id: 'pr3',
    nombre: 'Gestión Farmacéutica',
    tipo: 'misional',
    responsable: 'QF. Ana Suárez',
    objetivo: 'Garantizar el suministro oportuno y seguro de medicamentos',
    indicadores: [],
    documentos: ['d3'],
    riesgos: [],
  },
  {
    id: 'pr4',
    nombre: 'Gestión del Talento Humano',
    tipo: 'apoyo',
    responsable: 'Coordinadora Calidad',
    objetivo: 'Garantizar personal idóneo, capacitado y habilitado',
    indicadores: ['i3'],
    documentos: ['d5'],
    riesgos: [],
  },
  {
    id: 'pr5',
    nombre: 'Gestión de Calidad y Mejoramiento',
    tipo: 'evaluacion',
    responsable: 'Coordinadora Calidad',
    objetivo: 'Medir, analizar y mejorar continuamente los procesos del SGC',
    indicadores: ['i4'],
    documentos: ['d1'],
    riesgos: [],
  },
]

export const PQRS0: PQRS[] = [
  {
    id: 'pq1',
    tipo: 'queja',
    radicado: 'PQ-2025-001',
    fecha: '2025-02-10',
    sede: 'BAQ',
    nombreInteresado: 'María Fernández',
    contacto: '3001234567',
    descripcion: 'Demora de más de 2 horas para ser atendida en consulta',
    respuesta:
      'Se verificó el incidente. Se ajustó la agenda médica para reducir tiempos de espera.',
    fechaRespuesta: '2025-02-24',
    responsable: 'Aux. Administrativa',
    estado: 'cerrado',
  },
  {
    id: 'pq2',
    tipo: 'peticion',
    radicado: 'PQ-2025-002',
    fecha: '2025-03-05',
    sede: 'SIN',
    nombreInteresado: 'Carlos Ramos',
    contacto: '3151234567',
    descripcion: 'Solicita copia de su historia clínica',
    responsable: 'Coordinador Sincelejo',
    estado: 'en_tramite',
  },
]

export const ADHERENCIA0: Adherencia[] = [
  {
    id: 'adh1',
    protocolo: 'Lavado de manos clínico',
    sede: 'BAQ',
    periodo: '2025-T1',
    totalAplicaciones: 120,
    conformes: 108,
    noConformes: 12,
    observaciones: 'Se reforzó capacitación de técnica de lavado de manos',
    responsable: 'Jefe de Enfermería',
    fecha: '2025-04-05',
  },
  {
    id: 'adh2',
    protocolo: 'Verificación de 5 correctos en dispensación',
    sede: 'BAQ',
    periodo: '2025-T1',
    totalAplicaciones: 85,
    conformes: 82,
    noConformes: 3,
    observaciones: 'Cumplimiento satisfactorio',
    responsable: 'QF. Ana Suárez',
    fecha: '2025-04-05',
  },
]
