// ─── Seed data — réplica del stackblitz SGC Betania ─────────────────────────
import type {
  AccionPAMEC,
  Adherencia,
  AlertaSanitaria,
  Auditoria,
  CapacitacionProgramada,
  Cargo,
  Documento,
  Equipo,
  GPC,
  Habilitacion,
  Indicador,
  Mantenimiento,
  MedicionIndicador,
  Medicamento,
  PQRS,
  Persona,
  Proceso,
  RequisitoEstado,
  Sede,
  Usuario,
} from './types'
import { REQUISITOS_POR_CARGO } from './data-catalogs'

// ─── Usuarios (sesión mock) ──────────────────────────────────────────────────
export const USUARIOS: Usuario[] = [
  {
    id: 'u1',
    nombre: 'Juan Director',
    email: 'juan@betania.com',
    rol: 'director',
    sede: 'BAQ',
    clave: 'juan123',
  },
  {
    id: 'u2',
    nombre: 'Coord. Calidad',
    email: 'calidad@betania.com',
    rol: 'calidad',
    sede: 'BAQ',
    clave: 'calidad123',
  },
  {
    id: 'u3',
    nombre: 'Administrador SGC',
    email: 'admin@betania.com',
    rol: 'admin',
    sede: 'BAQ',
    clave: 'admin123',
  },
]

// ─── Sedes ───────────────────────────────────────────────────────────────────
export const SEDES0: Sede[] = [
  {
    id: 'BAQ',
    nombre: 'Betania Barranquilla',
    ciudad: 'Barranquilla',
    departamento: 'Atlántico',
    direccion: 'Cra. 38 #79-25',
    activa: true,
    servicios: ['Consulta externa', 'Hematología', 'Oncología', 'Infusión IV'],
  },
  {
    id: 'SIN',
    nombre: 'Betania Sincelejo',
    ciudad: 'Sincelejo',
    departamento: 'Sucre',
    direccion: 'Cl. 20 #25-30',
    activa: true,
    servicios: ['Consulta externa', 'Infusión IV'],
  },
  {
    id: 'STM',
    nombre: 'Betania Santa Marta',
    ciudad: 'Santa Marta',
    departamento: 'Magdalena',
    direccion: 'Av. del Río #15-40',
    activa: true,
    servicios: ['Consulta externa', 'Hematología', 'Oncología', 'Infusión IV'],
  },
  {
    id: 'MTR',
    nombre: 'Betania Montería',
    ciudad: 'Montería',
    departamento: 'Córdoba',
    direccion: 'Cl. 28 #5-60',
    activa: true,
    servicios: ['Consulta externa', 'Infusión IV'],
  },
]

// ─── Cargos (catálogo) ───────────────────────────────────────────────────────
export const CARGOS0: Cargo[] = [
  {
    id: 'MD',
    nombre: 'Médico Hematólogo',
    area: 'Asistencial',
    perfil: 'Médico con especialización en hematología',
    docRequeridos: ['tarjeta_profesional', 'rethus'],
    capRequeridas: ['acls', 'gpc_hemofilia', 'humanizacion'],
  },
  {
    id: 'MD_ONC',
    nombre: 'Médico Oncólogo',
    area: 'Asistencial',
    perfil: 'Médico con especialización en oncología',
    docRequeridos: ['tarjeta_profesional', 'rethus'],
    capRequeridas: ['bls', 'manejo_quimio'],
  },
  {
    id: 'MD_GEN',
    nombre: 'Médico General',
    area: 'Asistencial',
    perfil: 'Médico general con experiencia en atención ambulatoria',
    docRequeridos: ['tarjeta_profesional', 'rethus'],
    capRequeridas: ['bls'],
  },
  {
    id: 'ENF',
    nombre: 'Enfermera Jefe',
    area: 'Asistencial',
    perfil: 'Enfermero/a profesional jefe de servicio',
    docRequeridos: ['tarjeta_profesional', 'rethus'],
    capRequeridas: ['acls', 'manejo_ams'],
  },
  {
    id: 'AUX_ENF',
    nombre: 'Auxiliar de Enfermería',
    area: 'Asistencial',
    perfil: 'Técnico auxiliar de enfermería',
    docRequeridos: ['titulo_tecnico', 'rethus'],
    capRequeridas: ['bls', 'bioseguridad'],
  },
  {
    id: 'QF',
    nombre: 'Químico Farmacéutico',
    area: 'Asistencial',
    perfil: 'Químico farmacéutico titulado',
    docRequeridos: ['tarjeta_profesional', 'rethus'],
    capRequeridas: ['cadena_frio', 'manejo_citotoxicos'],
  },
  {
    id: 'ADM',
    nombre: 'Auxiliar Administrativo',
    area: 'Administrativa',
    perfil: 'Técnico o tecnólogo administrativo',
    docRequeridos: ['titulo_tecnico'],
    capRequeridas: ['atencion_usuario'],
  },
  {
    id: 'COORD_CAL',
    nombre: 'Coordinador de Calidad',
    area: 'Calidad',
    perfil: 'Profesional de salud con formación en gestión de calidad',
    docRequeridos: ['titulo_profesional', 'tarjeta_profesional'],
    capRequeridas: ['normas_iso', 'auditoria_interna'],
  },
]

// ─── Helper para generar requisitos semilla con distintos estados ────────────
function mkRequisitos(
  cargoId: string,
  overrides: Array<{
    defId: string
    estado: RequisitoEstado['estado']
    fechaVigencia?: string | null
  }>
): RequisitoEstado[] {
  const defs = REQUISITOS_POR_CARGO[cargoId] ?? []
  const overrideMap = new Map(overrides.map((o) => [o.defId, o]))
  return defs.map((def) => {
    const o = overrideMap.get(def.id)
    if (o)
      return {
        defId: def.id,
        estado: o.estado,
        fechaVigencia: o.fechaVigencia ?? null,
      }
    // Default: todo lo crítico sin override queda CRITICO (sin cargar), lo demás SIN_CARGAR
    return {
      defId: def.id,
      estado: def.critico ? 'CRITICO' : 'SIN_CARGAR',
      fechaVigencia: null,
    }
  })
}

// ─── Personas (7) ────────────────────────────────────────────────────────────
export const PERS0: Persona[] = [
  {
    id: 'p1',
    nombre: 'Dr. Andrés Ospino',
    cedula: '72123456',
    cargo: 'MD',
    sede: 'BAQ',
    fechaIngreso: '2020-03-01',
    estado: 'activo',
    docs: [],
    caps: [],
    requisitos: mkRequisitos('MD', [
      { defId: 'rq_rethus', estado: 'VENCIDO', fechaVigencia: '2025-08-15' },
      { defId: 'rq_acls', estado: 'POR_VALIDAR', fechaVigencia: '2026-01-10' },
    ]),
  },
  {
    id: 'p2',
    nombre: 'Enf. Claudia Martínez',
    cedula: '32456789',
    cargo: 'ENF',
    sede: 'BAQ',
    fechaIngreso: '2021-07-01',
    estado: 'activo',
    docs: [],
    caps: [],
    requisitos: mkRequisitos('ENF', [
      { defId: 'rq_tp_enf', estado: 'VENCIDO', fechaVigencia: '2026-03-10' },
      {
        defId: 'rq_rethus_enf',
        estado: 'VENCIDO',
        fechaVigencia: '2026-03-10',
      },
      { defId: 'rq_ams_enf', estado: 'VENCIDO', fechaVigencia: '2025-09-20' },
    ]),
  },
  {
    id: 'p3',
    nombre: 'Dr. Luis Palomino',
    cedula: '82345678',
    cargo: 'MD_GEN',
    sede: 'SIN',
    fechaIngreso: '2022-02-15',
    estado: 'activo',
    docs: [],
    caps: [],
    requisitos: [
      { defId: 'rq_rethus', estado: 'CRITICO', fechaVigencia: null },
      { defId: 'rq_tp', estado: 'CRITICO', fechaVigencia: null },
      { defId: 'rq_bls', estado: 'CRITICO', fechaVigencia: null },
      { defId: 'rq_vacunas', estado: 'CRITICO', fechaVigencia: null },
    ],
  },
  {
    id: 'p4',
    nombre: 'Enf. Patricia Díaz',
    cedula: '45678901',
    cargo: 'AUX_ENF',
    sede: 'STM',
    fechaIngreso: '2023-01-10',
    estado: 'activo',
    docs: [],
    caps: [],
    requisitos: mkRequisitos('AUX_ENF', [
      { defId: 'rq_titulo_aux', estado: 'VIGENTE', fechaVigencia: null },
      {
        defId: 'rq_rethus_aux',
        estado: 'VIGENTE',
        fechaVigencia: '2027-05-10',
      },
    ]),
  },
  {
    id: 'p5',
    nombre: 'Quím. Mario Herrera',
    cedula: '98765432',
    cargo: 'QF',
    sede: 'MTR',
    fechaIngreso: '2021-11-20',
    estado: 'activo',
    docs: [],
    caps: [],
    requisitos: mkRequisitos('QF', [
      { defId: 'rq_tp_qf', estado: 'VIGENTE', fechaVigencia: null },
    ]),
  },
  {
    id: 'p6',
    nombre: 'Dra. Sandra Roa',
    cedula: '52345678',
    cargo: 'MD_ONC',
    sede: 'BAQ',
    fechaIngreso: '2020-05-01',
    estado: 'activo',
    docs: [],
    caps: [],
    requisitos: [
      { defId: 'rq_diploma', estado: 'CRITICO', fechaVigencia: null },
      { defId: 'rq_acta_grado', estado: 'CRITICO', fechaVigencia: null },
      { defId: 'rq_acta_esp', estado: 'CRITICO', fechaVigencia: null },
      { defId: 'rq_convalidacion', estado: 'CRITICO', fechaVigencia: null },
      { defId: 'rq_bls', estado: 'CRITICO', fechaVigencia: null },
      {
        defId: 'rq_qt',
        estado: 'POR_VALIDAR',
        fechaVigencia: '2025-11-15',
      },
      { defId: 'rq_violencia', estado: 'CRITICO', fechaVigencia: null },
      { defId: 'rq_humanizacion', estado: 'CRITICO', fechaVigencia: null },
    ],
  },
  {
    id: 'p7',
    nombre: 'Enf. Rosa Berrío',
    cedula: '60123456',
    cargo: 'AUX_ENF',
    sede: 'SIN',
    fechaIngreso: '2022-08-15',
    estado: 'activo',
    docs: [],
    caps: [],
    requisitos: mkRequisitos('AUX_ENF', []),
  },
]

// ─── Equipos biomédicos (6) ─────────────────────────────────────────────────
export const EQS0: Equipo[] = [
  {
    id: 'SIG-001',
    nombre: 'Bomba de Infusión IV',
    marca: 'Baxter',
    modelo: 'SIGMA Spectrum',
    serie: 'SIG-001',
    sede: 'BAQ',
    area: 'Sala de infusión',
    fechaCompra: '2022-06-10',
    ultimaMant: '2024-10-15',
    proxMant: '2025-04-15',
    estado: 'operativo',
    invima: 'INVIMA 2020DM-0001',
    vida: 10,
    prioridad: 'alta',
    docs: [],
  },
  {
    id: 'SIG-002',
    nombre: 'Bomba de Infusión IV',
    marca: 'Baxter',
    modelo: 'SIGMA Spectrum',
    serie: 'SIG-002',
    sede: 'BAQ',
    area: 'Sala de infusión',
    fechaCompra: '2022-06-10',
    ultimaMant: '2024-10-15',
    proxMant: '2025-04-15',
    estado: 'operativo',
    invima: 'INVIMA 2020DM-0001',
    vida: 10,
    prioridad: 'alta',
    docs: [],
  },
  {
    id: 'MEC-001',
    nombre: 'Monitor Signos Vitales',
    marca: 'Mindray',
    modelo: 'MEC-1200',
    serie: 'MEC-001',
    sede: 'SIN',
    area: 'Urgencias',
    fechaCompra: '2021-02-10',
    ultimaMant: '2024-11-20',
    proxMant: '2025-05-20',
    estado: 'operativo',
    invima: 'INVIMA 2020DM-0456',
    vida: 10,
    prioridad: 'alta',
    docs: [],
  },
  {
    id: 'AGI-001',
    nombre: 'Bomba de Infusión IV',
    marca: 'Fresenius',
    modelo: 'Agilia',
    serie: 'AGI-001',
    sede: 'STM',
    area: 'Sala de infusión',
    fechaCompra: '2020-09-01',
    ultimaMant: '2024-09-05',
    proxMant: '2025-03-05',
    estado: 'operativo',
    invima: 'INVIMA 2019DM-0789',
    vida: 10,
    prioridad: 'alta',
    docs: [],
  },
  {
    id: 'HLR-001',
    nombre: 'Refrigerador Médico',
    marca: 'Helmer',
    modelo: 'HLR-105',
    serie: 'HLR-001',
    sede: 'MTR',
    area: 'Farmacia',
    fechaCompra: '2019-07-15',
    ultimaMant: '2024-08-01',
    proxMant: '2025-02-01',
    estado: 'operativo',
    invima: 'INVIMA 2018DM-0234',
    vida: 15,
    prioridad: 'alta',
    docs: [],
  },
  {
    id: 'MEC-002',
    nombre: 'Monitor Signos Vitales',
    marca: 'Mindray',
    modelo: 'MEC-2000',
    serie: 'MEC-002',
    sede: 'MTR',
    area: 'Consulta externa',
    fechaCompra: '2023-01-05',
    ultimaMant: '2025-01-10',
    proxMant: '2025-07-10',
    estado: 'operativo',
    invima: 'INVIMA 2020DM-0456',
    vida: 10,
    prioridad: 'alta',
    docs: [],
  },
]

// ─── Habilitación por sede (estado del checklist por sede) ──────────────────
export const HAB0: Record<string, Habilitacion> = {
  BAQ: {
    sedeId: 'BAQ',
    fechaRevision: '2026-04-14',
    responsable: 'Coord. Calidad',
    items: [],
  },
  SIN: {
    sedeId: 'SIN',
    fechaRevision: '2026-04-14',
    responsable: 'Coord. Calidad',
    items: [],
  },
  STM: {
    sedeId: 'STM',
    fechaRevision: '2026-04-14',
    responsable: 'Coord. Calidad',
    items: [],
  },
  MTR: {
    sedeId: 'MTR',
    fechaRevision: '2026-04-14',
    responsable: 'Coord. Calidad',
    items: [],
  },
}

// ─── Indicadores (definiciones) ──────────────────────────────────────────────
export const INDIC_DEF: Indicador[] = [
  {
    id: 'i_th_caps_ejec',
    nombre: '% capacitaciones ejecutadas',
    descripcion: 'Capacitaciones con estado Ejecutada / total programadas',
    formula: '(Ejecutadas / Programadas) × 100',
    meta: 80,
    unidad: '%',
    frecuencia: 'mensual',
    proceso: 'Talento Humano',
    responsable: 'Coord. Calidad',
  },
  {
    id: 'i_th_doc_completa',
    nombre: '% personal con documentación completa',
    descripcion: 'Personas con todos los requisitos documentales validados',
    formula: '(Personas completas / Total personas) × 100',
    meta: 100,
    unidad: '%',
    frecuencia: 'mensual',
    proceso: 'Talento Humano',
    responsable: 'Coord. Calidad',
  },
  {
    id: 'i_th_caps_norm',
    nombre: '% capacitaciones normativas ejecutadas',
    descripcion: 'Capacitaciones obligatorias por norma con estado Ejecutada',
    formula: '(Ejecutadas normativas / Programadas normativas) × 100',
    meta: 100,
    unidad: '%',
    frecuencia: 'mensual',
    proceso: 'Talento Humano',
    responsable: 'Coord. Calidad',
  },
  {
    id: 'i_eq_mant',
    nombre: '% equipos con mantenimiento vigente',
    descripcion: 'Equipos con próximo mantenimiento en fecha futura / total',
    formula: '(Mant. vigentes / Total equipos) × 100',
    meta: 100,
    unidad: '%',
    frecuencia: 'mensual',
    proceso: 'Dotación',
    responsable: 'Coord. Calidad',
  },
  {
    id: 'i_eq_calib',
    nombre: '% equipos con calibración vigente',
    descripcion: 'Equipos con calibración vigente / total',
    formula: '(Calibración vigente / Total equipos) × 100',
    meta: 100,
    unidad: '%',
    frecuencia: 'mensual',
    proceso: 'Dotación',
    responsable: 'Coord. Calidad',
  },
  {
    id: 'i_eq_hv',
    nombre: '% HV técnicas cargadas en equipos',
    descripcion: 'Equipos con link HV técnica cargado / total',
    formula: '(Con HV / Total) × 100',
    meta: 100,
    unidad: '%',
    frecuencia: 'mensual',
    proceso: 'Dotación',
    responsable: 'Coord. Calidad',
  },
  {
    id: 'i_hab_check',
    nombre: '% checklist habilitación cumplido',
    descripcion: 'Promedio de ítems cumplidos por sede habilitada',
    formula: 'avg(Cumple / Total ítems) × 100',
    meta: 100,
    unidad: '%',
    frecuencia: 'trimestral',
    proceso: 'Habilitación',
    responsable: 'Coord. Calidad',
  },
  {
    id: 'i_doc_vigentes',
    nombre: '% documentos vigentes',
    descripcion: 'Documentos con estado Vigente / total',
    formula: '(Vigentes / Total) × 100',
    meta: 100,
    unidad: '%',
    frecuencia: 'mensual',
    proceso: 'Gestión Documental',
    responsable: 'Coord. Calidad',
  },
  {
    id: 'i_doc_sp',
    nombre: '% documentos con SP cargado',
    descripcion: 'Documentos con link SharePoint cargado / total',
    formula: '(Con SP / Total) × 100',
    meta: 100,
    unidad: '%',
    frecuencia: 'mensual',
    proceso: 'Gestión Documental',
    responsable: 'Coord. Calidad',
  },
  {
    id: 'i_pqrs_termino',
    nombre: '% PQRS respondidas en término',
    descripcion: 'PQRS cerradas dentro de 15 días hábiles / total cerradas',
    formula: '(A término / Cerradas) × 100',
    meta: 95,
    unidad: '%',
    frecuencia: 'mensual',
    proceso: 'Satisfacción',
    responsable: 'Coord. Calidad',
  },
  {
    id: 'i_pqrs_tiempo',
    nombre: 'Tiempo promedio respuesta PQRS (días)',
    descripcion: 'Promedio de días entre recepción y cierre de PQRS',
    formula: 'avg(días entre recepción y cierre)',
    meta: 15,
    unidad: 'días',
    frecuencia: 'mensual',
    proceso: 'Satisfacción',
    responsable: 'Coord. Calidad',
  },
  {
    id: 'i_gpc_adh',
    nombre: '% adherencia a GPC (promedio)',
    descripcion: 'Promedio de adherencia a todas las GPC medidas en el período',
    formula: 'avg(% adherencia por GPC)',
    meta: 95,
    unidad: '%',
    frecuencia: 'trimestral',
    proceso: 'Pertinencia',
    responsable: 'Coord. Calidad',
  },
  {
    id: 'i_med_alertas',
    nombre: '% alertas sanitarias con acción',
    descripcion: 'Alertas sanitarias con acción tomada registrada / total',
    formula: '(Con acción / Total) × 100',
    meta: 100,
    unidad: '%',
    frecuencia: 'mensual',
    proceso: 'Medicamentos y DM',
    responsable: 'Coord. Calidad',
  },
  {
    id: 'i_mant_cerradas',
    nombre: '% solicitudes mantenimiento cerradas',
    descripcion: 'Solicitudes de mantenimiento con estado Cerrado / total',
    formula: '(Cerradas / Total) × 100',
    meta: 80,
    unidad: '%',
    frecuencia: 'mensual',
    proceso: 'Mantenimiento',
    responsable: 'Coord. Calidad',
  },
]

export const MEDICIONES0: MedicionIndicador[] = []

// ─── PAMEC: plan de mejoramiento ─────────────────────────────────────────────
export const PLAN_MEJORA0: AccionPAMEC[] = [
  {
    id: 'am1',
    hallazgo: 'Protocolo de manejo seguro de medicamentos no socializado',
    causa: 'Alta rotación de personal y falta de cronograma formal',
    accion:
      'Elaborar cronograma de socialización trimestral y registrar asistencia',
    responsable: 'Coord. Calidad',
    fechaLimite: '2025-12-31',
    estado: 'vencido',
    fase: 'planear',
    sede: 'SIN',
  },
]

// ─── Auditorías (3) ─────────────────────────────────────────────────────────
export const AUDITORIAS0: Auditoria[] = [
  {
    id: 'AUD-2025-001',
    tipo: 'interna',
    proceso: 'Talento Humano',
    sede: 'BAQ',
    auditor: 'Coord. Calidad',
    fechaInicio: '2025-05-15',
    fechaFin: '2025-05-15',
    estado: 'planeada',
    hallazgos: [],
    observaciones: 'Auditoría programada sobre requisitos documentales',
  },
  {
    id: 'AUD-2025-002',
    tipo: 'interna',
    proceso: 'Equipos Biomédicos',
    sede: 'TODAS',
    auditor: 'Coord. Calidad',
    fechaInicio: '2025-06-10',
    fechaFin: '2025-06-12',
    estado: 'planeada',
    hallazgos: [],
    observaciones: 'Auditoría de equipos biomédicos en todas las sedes',
  },
  {
    id: 'AUD-2024-004',
    tipo: 'seguimiento',
    proceso: 'Habilitación',
    sede: 'SIN',
    auditor: 'Coord. Calidad',
    fechaInicio: '2024-11-20',
    fechaFin: '2024-11-20',
    estado: 'cerrada',
    hallazgos: [
      {
        id: 'h1',
        tipo: 'no_conformidad',
        descripcion: 'Procedimientos nuevos sin socialización documentada',
        criterio: 'Res. 3100/2019',
        estado: 'abierto',
        accionCorrectiva: 'Elaborar cronograma de socialización trimestral',
        responsable: 'Coord. Calidad',
        fechaLimite: '2025-12-31',
      },
      {
        id: 'h2',
        tipo: 'observacion',
        descripcion: 'Registros de capacitación sin firma de asistencia',
        criterio: 'Res. 3100/2019',
        estado: 'cerrado',
      },
    ],
    observaciones:
      'Seguimiento a plan de habilitación — 2 hallazgos identificados',
  },
]

// ─── Documentos (10) ─────────────────────────────────────────────────────────
export const DOCS0: Documento[] = [
  {
    id: 'GC-MA-001',
    codigo: 'GC-MA-001',
    nombre: 'Manual de Calidad Betania',
    tipo: 'manual',
    proceso: 'Gestión de calidad',
    version: 'v3.0',
    fechaElaboracion: '2024-01-15',
    fechaVigencia: '2025-01-15',
    responsable: 'Coord. Calidad',
    estado: 'vigente',
  },
  {
    id: 'GC-PO-001',
    codigo: 'GC-PO-001',
    nombre: 'Política de Seguridad del Paciente',
    tipo: 'politica',
    proceso: 'Seguridad del paciente',
    version: 'v2.1',
    fechaElaboracion: '2024-03-10',
    fechaVigencia: '2025-03-10',
    responsable: 'Dir. Médico',
    estado: 'vigente',
  },
  {
    id: 'AT-PR-001',
    codigo: 'AT-PR-001',
    nombre: 'Protocolo Manejo Hemofilia – Infusión IV',
    tipo: 'protocolo',
    proceso: 'Atención al paciente',
    version: 'v4.0',
    fechaElaboracion: '2024-06-01',
    fechaVigencia: '2025-06-01',
    responsable: 'Dir. Médico',
    estado: 'vigente',
  },
  {
    id: 'AT-GPC-001',
    codigo: 'AT-GPC-001',
    nombre: 'GPC Hemofilia – Diagnóstico y Tratamiento',
    tipo: 'guia_practica_clinica',
    proceso: 'Atención al paciente',
    version: 'v1.2',
    fechaElaboracion: '2023-11-20',
    fechaVigencia: '2024-11-20',
    responsable: 'Dir. Médico',
    estado: 'en_revision',
  },
  {
    id: 'TH-PR-001',
    codigo: 'TH-PR-001',
    nombre: 'Procedimiento Gestión Hojas de Vida',
    tipo: 'procedimiento',
    proceso: 'Talento humano',
    version: 'v2.0',
    fechaElaboracion: '2026-02-01',
    fechaVigencia: '2027-02-01',
    responsable: 'Coord. Calidad',
    estado: 'vigente',
  },
  {
    id: 'EQ-PR-001',
    codigo: 'EQ-PR-001',
    nombre: 'Procedimiento Mantenimiento Biomédico',
    tipo: 'procedimiento',
    proceso: 'Gestión de equipos',
    version: 'v1.5',
    fechaElaboracion: '2024-04-15',
    fechaVigencia: '2025-04-15',
    responsable: 'Coord. Calidad',
    estado: 'vigente',
  },
  {
    id: 'GC-PR-002',
    codigo: 'GC-PR-002',
    nombre: 'Procedimiento Gestión de PQR',
    tipo: 'procedimiento',
    proceso: 'PQR',
    version: 'v2.2',
    fechaElaboracion: '2024-07-01',
    fechaVigencia: '2025-07-01',
    responsable: 'Coord. Calidad',
    estado: 'vigente',
  },
  {
    id: 'SP-PR-001',
    codigo: 'SP-PR-001',
    nombre: 'Protocolo Manejo Eventos Adversos',
    tipo: 'protocolo',
    proceso: 'Seguridad del paciente',
    version: 'v3.1',
    fechaElaboracion: '2024-05-20',
    fechaVigencia: '2025-05-20',
    responsable: 'Coord. Calidad',
    estado: 'en_aprobacion',
  },
  {
    id: 'FIN-CE-001',
    codigo: 'FIN-CE-001',
    nombre: 'Certificado Suficiencia Patrimonial',
    tipo: 'certificado',
    proceso: 'Gestión financiera',
    version: 'v1.0',
    fechaElaboracion: '2025-01-15',
    fechaVigencia: '2026-01-15',
    responsable: 'Dir. Administrativo',
    estado: 'vigente',
  },
  {
    id: 'FIN-PO-001',
    codigo: 'FIN-PO-001',
    nombre: 'Póliza Responsabilidad Civil Extracontractual',
    tipo: 'poliza',
    proceso: 'Gestión financiera',
    version: 'v1.0',
    fechaElaboracion: '2025-02-01',
    fechaVigencia: '2026-02-01',
    responsable: 'Dir. Administrativo',
    estado: 'vigente',
  },
]

// ─── Mantenimientos (3) ──────────────────────────────────────────────────────
export const MANTENIMIENTOS0: Mantenimiento[] = [
  {
    id: 'MNT-2025-001',
    codigo: 'MNT-2025-001',
    descripcion:
      'Alarma de oclusión activa de forma intermitente sin causa aparente. Equipo fuera de servicio.',
    tipo: 'biomedico',
    sedeId: 'BAQ',
    area: 'Sala de infusión',
    prioridad: 'alta',
    solicitante: 'Enf. Claudia Martínez',
    apertura: '2025-03-10',
    estado: 'en_ejecucion',
  },
  {
    id: 'MNT-2025-002',
    codigo: 'MNT-2025-002',
    descripcion:
      'Filtro de aire acondicionado obstruido. Olores y temperatura inadecuada para pacientes.',
    tipo: 'infraestructura',
    sedeId: 'SIN',
    area: 'Sala de espera',
    prioridad: 'media',
    solicitante: 'Dr. Luis Palomino',
    apertura: '2025-03-15',
    estado: 'cerrado',
  },
  {
    id: 'MNT-2025-003',
    codigo: 'MNT-2025-003',
    descripcion:
      'Computador de recepción presenta lentitud extrema al abrir el sistema de historias clínicas.',
    tipo: 'ti',
    sedeId: 'BAQ',
    area: 'Recepción',
    prioridad: 'baja',
    solicitante: 'Coord. Calidad',
    apertura: '2025-04-01',
    estado: 'abierto',
  },
]

// ─── PQRS (3) ────────────────────────────────────────────────────────────────
export const PQRS0: PQRS[] = [
  {
    id: 'PQR-2026-001',
    tipo: 'queja',
    radicado: 'PQR-2026-001',
    fecha: '2026-03-10',
    sede: 'BAQ',
    nombreInteresado: 'María Fernández',
    contacto: '3001234567',
    descripcion:
      'Demora en la atención en sala de infusión — paciente esperó más de 2 horas.',
    responsable: 'Coord. Calidad',
    estado: 'en_tramite',
  },
  {
    id: 'PQR-2026-002',
    tipo: 'peticion',
    radicado: 'PQR-2026-002',
    fecha: '2026-03-15',
    sede: 'SIN',
    nombreInteresado: 'Carlos Ramos',
    contacto: '3151234567',
    descripcion: 'Solicitud de copia de historia clínica.',
    respuesta: 'Se entregó copia en fecha 25/03/2026.',
    fechaRespuesta: '2026-03-25',
    responsable: 'Admisionista',
    estado: 'cerrado',
  },
  {
    id: 'PQR-2026-003',
    tipo: 'reclamo',
    radicado: 'PQR-2026-003',
    fecha: '2026-04-01',
    sede: 'BAQ',
    nombreInteresado: 'Luis Pérez',
    contacto: '3012345678',
    descripcion: 'Cobro indebido por medicamento no POS.',
    responsable: 'Coord. Calidad',
    estado: 'vencido',
  },
]

// ─── Adherencia a protocolos (por GPC) ──────────────────────────────────────
export const ADHERENCIA0: Adherencia[] = [
  {
    id: 'adh1',
    protocolo: 'GPC Hemofilia – Diagnóstico',
    sede: 'BAQ',
    periodo: '2026-T1',
    totalAplicaciones: 50,
    conformes: 46,
    noConformes: 4,
    observaciones: 'Adherencia aceptable',
    responsable: 'Dir. Médico',
    fecha: '2026-04-05',
  },
  {
    id: 'adh2',
    protocolo: 'Protocolo identificación del paciente',
    sede: 'BAQ',
    periodo: '2026-T1',
    totalAplicaciones: 200,
    conformes: 184,
    noConformes: 16,
    observaciones: 'Plan de refuerzo en puntos de admisión',
    responsable: 'Coord. Calidad',
    fecha: '2026-04-05',
  },
  {
    id: 'adh3',
    protocolo: 'Protocolo administración medicamentos',
    sede: 'BAQ',
    periodo: '2026-T1',
    totalAplicaciones: 150,
    conformes: 135,
    noConformes: 15,
    observaciones: '',
    responsable: 'Coord. Calidad',
    fecha: '2026-04-05',
  },
  {
    id: 'adh4',
    protocolo: 'Lavado de manos clínico',
    sede: 'BAQ',
    periodo: '2026-T1',
    totalAplicaciones: 300,
    conformes: 270,
    noConformes: 30,
    observaciones: 'Reforzar con observación directa',
    responsable: 'Jefe de Enfermería',
    fecha: '2026-04-05',
  },
]

// ─── GPCs (catálogo) ────────────────────────────────────────────────────────
export const GPCS0: GPC[] = [
  {
    id: 'gpc1',
    nombre: 'GPC Hemofilia – Diagnóstico y Tratamiento',
    adherenciaPromedio: 92,
    ultimaMedicion: '2026-04-05',
  },
  {
    id: 'gpc2',
    nombre: 'GPC Trombocitopenia Inmune',
    adherenciaPromedio: 88,
    ultimaMedicion: '2026-03-20',
  },
  {
    id: 'gpc3',
    nombre: 'GPC Linfoma No Hodgkin',
    adherenciaPromedio: 89,
    ultimaMedicion: '2026-03-25',
  },
  {
    id: 'gpc4',
    nombre: 'GPC Leucemia Aguda',
    adherenciaPromedio: 90.5,
    ultimaMedicion: '2026-04-10',
  },
]

// ─── Capacitaciones que requieren atención ──────────────────────────────────
export const CAPACITACIONES_PROGRAMADAS0: CapacitacionProgramada[] = [
  {
    id: 'cap1',
    nombre: 'Humanización en salud — trato digno al usuario',
    area: 'Administrativa',
    fechaObjetivo: '2026-03-01',
    estado: 'vencida',
  },
  {
    id: 'cap2',
    nombre: 'Manejo seguro de medicamentos de alto riesgo',
    area: 'Enfermería',
    fechaObjetivo: '2026-04-20',
    estado: 'programada',
  },
  {
    id: 'cap3',
    nombre: 'Bioseguridad y manejo de residuos',
    area: 'Asistencial',
    fechaObjetivo: '2026-02-15',
    estado: 'ejecutada',
  },
  {
    id: 'cap4',
    nombre: 'Soporte Vital Avanzado (ACLS)',
    area: 'Asistencial',
    fechaObjetivo: '2026-06-01',
    estado: 'programada',
  },
  {
    id: 'cap5',
    nombre: 'Farmacovigilancia',
    area: 'Farmacia',
    fechaObjetivo: '2026-05-10',
    estado: 'programada',
  },
]

// ─── Alertas sanitarias ──────────────────────────────────────────────────────
export const ALERTAS_SANITARIAS0: AlertaSanitaria[] = []

// ─── Medicamentos (legacy — mantener para backward compat) ──────────────────
export const MEDS0: Medicamento[] = []

// ─── Procesos (legacy) ──────────────────────────────────────────────────────
export const PROCESOS0: Proceso[] = []
